name: cypress cloud app 

on:
  workflow_dispatch:
    inputs:
      amb:
        description: 'Select environment: development / production'
        required: false
        default: 'production'
      browser:
        description: 'Select browser: chrome / electron'
        required: false
        default: 'chrome'
  pull_request:
    branches: [ main, release/develop ]
    
env:
  DEFAULT_AMB: "production"
  DEFAULT_BROWSER: "chrome"

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build    
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88
    needs: install
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run 
        uses: cypress-io/github-action@v2
        with: 
          command: npx cypress run --config-file config/${{github.event.inputs.amb || env.DEFAULT_AMB}}.json --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}} --record --key 8a739225-a680-4dda-96d1-f7e2ace426d8
      